# See https://aka.ms/yaml

trigger:
  - master
  - v*.*.x
pr:
  - master
  - v*.*.x

stages:
  - stage: Build
    jobs:
      - job: build
        strategy:
          matrix:
            spark-2.3:
              spark_version: "2.3"
            spark-2.4:
              spark_version: "2.4"
        pool:
          vmImage: 'ubuntu-16.04'
          demands: Maven
        steps:
          - task: Maven@3
            displayName:  build
            inputs:
              jdkVersionOption: "1.8"
              publishJUnitResults: false
              goals: "package"
              options: "-B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Pspark-$(spark_version)"
          - task: Maven@3
            displayName: sonar
            inputs:
              jdkVersionOption: "1.8"
              publishJUnitResults: false
              goals: "sonar:sonar"
              options: "-B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -Dsonar.projectKey=openucx:spark-ucx -Dsonar.organization=openucx -Pspark-$(spark_version) -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=97f4df88ff4fa04e2d5b061acf07315717f1f08b"
          - publish: '$(System.DefaultWorkingDirectory)/'
            artifact: jar for spark-$(spark_version)
            displayName: Publish jars

